[main]
user.loginUrl = /login.xhtml


dataSource = org.apache.shiro.jndi.JndiObjectFactory
dataSource.resourceName = java:comp/env/myDataSource


#jdbcRealm.authorizationCachingEnabled = false

jdbcRealm = org.apache.shiro.realm.jdbc.JdbcRealm
jdbcRealm.dataSource = $dataSource


jdbcRealm.authenticationQuery = SELECT password FROM USER_ WHERE username = ?
jdbcRealm.userRolesQuery = SELECT role FROM user_roles WHERE username = ?

credentialsMatcher = org.apache.shiro.authc.credential.SimpleCredentialsMatcher
jdbcRealm.credentialsMatcher = $credentialsMatcher


shiro.loginUrl = /login.xhtml




[urls]
/online/** = user
/login.xhtml = anon
/** = anon